# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       Jamie McLeish's Blog - Tech Ramblings
email:       'jamie@jamiemcl.tech'
description: 'A blog to house all of the tech thoughts running around my head'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://jamiemcl.tech/' # The base hostname & protocol for your site
twitter:     'https://twitter.com/jamie_mcleish'
github:      'https://github.com/jamiemcl001'
instagram:   'https://www.instagram.com/jamie_mcleish91/'
facebook:    'https://www.facebook.com/jamiemcleish'

markdown:    kramdown
permalink:   pretty
paginate:    10

kramdown:
  input: GFM

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-feed

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext